language: generic

sudo: required

branches:
    only:
        - master

services:
    - docker

# separate build jobs for time limit
script:
    - make build/linux-setup-base
    - make build/linux-setup-combine

after_success:
    - bash <(curl -s https://codecov.io/bash)
